name: CHILD_WORKFLOWS_ANOTHER_REPO
on: workflow_call
jobs:
  child-job:
    runs-on: ubuntu-latest
    steps:
      - name: child_workflow
        run: |
          echo "Event name - ${{ github.event_name }}"
          echo "trigger actor name  - ${{ github.triggering_actor }}"
      
