name: GHA_env_variable
on: workflow_dispatch
jobs:
  env_variable:
    environment: test
    env:
      USERNAME: ${{secrets.USERNAME}}
      PASSWORD: ${{secrets.PASSWORD}}
    runs-on: ubuntu-latest
    steps:
      - name: print secret env var
        run : |
          echo "GHA env username is - $USERNAME
          echo "GHA env password is - $PASSWORD

  test_evn_variable:
    runs-on: ubuntu-latest
    steps:
      - name: print env var
        run: echo "Environment variable is - $PORT"
