name: GHA_env_variable
on: workflow_dispatch
env:
  PORT: ${{vars.PORT}}
jobs:
  secret_env_var:
    environment: test
    env:
      USERNAME: ${{secrets.USERNAME}}
      PASSWORD: ${{secrets.PASSWORD}}
    runs-on: ubuntu-latest
    steps:
      - name: print secret env var
        run : |
          echo "GHA env username is - $USERNAME
          echo "GHA env password is - $PASSWORD

  evn_variable:
    runs-on: ubuntu-latest
    steps:
      - name: print env var
        run: echo "Environment variable is - $PORT"

  set_env_variable:
    runs-on: ubuntu-latest
    steps:
      - name: set env var
        run: echo "NAME=sham...!" >> $GITHUB_ENV

      - name: access env var
        run: echo "Env varible value is - $NAME"
